### ISSUE TITLE
Nano's pins A6 and A7 marked as "Digital Pins" on pinout diagram

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#11475]
https://store.arduino.cc/arduino-nano

On the "Pinout Diagram", both the summary as well as the full version, pins A6 and A7 are incorrectly marked as having "Digital Pin" capabilities.

On the classic Nano, these pins only have ADC capabilities, and can not be used as digital input or outputs.

---
Originally reported at:
https://forum.arduino.cc/t/nano-a6-a7-as-digital-i-o-reference-needed/856654/5

**Comment by oqibidipo** [comment]
Also, under Tech Specs it says
> Digital I/O Pins    22 (6 of which are PWM)

On the other hand, for Uno it says
> Digital I/O Pins   14 (of which 6 provide PWM output)

**Comment by per1234** [comment]
>Also, under Tech Specs it says

That documentation error is being tracked here: https://github.com/arduino/Arduino/issues/6313

**Comment by FunzioneFabio** [comment]
Thank you Per for pointing out this, the pinout is now corrected and online!
https://content.arduino.cc/assets/Pinout-NANO_latest.pdf
https://store.arduino.cc/arduino-nano

**Comment by SimonJohnCastle** [comment]
This item is not completly solved.
The wrong diagram with D20 and D21 is still showing if you go to [https://docs.arduino.cc/hardware/nano](https://docs.arduino.cc/hardware/nano) and press the PINOUT button

**Comment by FunzioneFabio** [comment]
@SimonJohnCastle Thank you for pointing that out, they are now updated!
@kengdahl you can close the issue.
