### ISSUE TITLE
WebServer example doesn't compile on DUE

### ISSUE THREAD

**Issue by qbahn21** [arduino/Arduino#4072]
Hi.
I got an error: 'SPI_CS' was not declared in this scope... There is no defnition of 'SPI_CS' in 5100.h I've found: ETHERNET_SHIELD_SPI_CS only.

**Comment by cmaglie** [comment]
@qbahn21 thanks for the report, it is now fixed in version 1.1.1.
The release should be available from library manager within an hour.

**Comment by qbahn21** [comment]
Hello.
Thanks for info. I don't see any new release right now. The latest release
is 1.0.5.

2015-11-05 19:25 GMT+01:00 Cristian Maglie <notifications@github.com>:

**Comment by cmaglie** [comment]
uhm... that's really weird, my minimum expectation is that you have 1.1.0 installed because is the release that shows the bug. Here is what I see from the library manager:

![eth](https://cloud.githubusercontent.com/assets/423515/10998976/901005be-8499-11e5-9049-0fe947d816c7.png)

so the release `1.1.1` has been published.
It may be that the library_index.json is not updated for some reason (file permission)? Does the IDE shows errors when you open the library manager?

**Comment by qbahn21** [comment]
No, it doesn't.
I have a several Arduino versions folders (installed one and few non
admin). Has it influence? I think it has, because I see, that there is
Ethernet version 1.1.0 in 1.6.6 library folder. I think that GUI reads
config from an old (1.0.6) installed version folder
(Users...\AppData\Local...). Is there any possibility to change this
behaviour?

**Comment by cmaglie** [comment]
The library manager lists the libraries found in the sketchbook folder, but I think that there is something more in your installation that is "confusing" the lib manager.
Let's try this:
* turn on verbose compile from preferences
* compile an Ehternet library example
* copy & paste here the output of the build, in particular the last part that shows all copies of Ethernet libraries available (and which one has been selected by the IDE).

**Comment by qbahn21** [comment]
Ok, let's try this method :) Error log in attachment.

[image: Obraz w treści 2]

2015-11-06 17:22 GMT+01:00 Cristian Maglie <notifications@github.com>:

> The library manager lists the libraries found in the sketchbook folder,
> but I think that there is something more in your installation that is
> "confusing" the lib manager.
> Let's try this:
>
>    - turn on verbose compile from preferences
>    - compile an Ehternet library example
>    - copy & paste here the output of the build, in particular the last
>    part that shows all copies of Ethernet libraries available (and which one
>    has been selected by the IDE).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/4072#issuecomment-154456980>.
>

Arduino: 1.6.6 (Windows 7), Board: "Arduino Due (Programming Port)"

D:\Pobrane\arduino-1.6.6\arduino-builder -dump-prefs -logger=machine -hardware "D:\Pobrane\arduino-1.6.6\hardware" -hardware "C:\Users\jdn\AppData\Local\Arduino15\packages" -tools "D:\Pobrane\arduino-1.6.6\tools-builder" -tools "D:\Pobrane\arduino-1.6.6\hardware\tools\avr" -tools "C:\Users\jdn\AppData\Local\Arduino15\packages" -built-in-libraries "D:\Pobrane\arduino-1.6.6\libraries" -libraries "C:\Users\jdn\Documents\Arduino\libraries" -fqbn=arduino:sam:arduino_due_x_dbg -vid-pid=0X2341_0X003D -ide-version=10606 -build-path "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\examples\WebServer\WebServer.ino"
D:\Pobrane\arduino-1.6.6\arduino-builder -compile -logger=machine -hardware "D:\Pobrane\arduino-1.6.6\hardware" -hardware "C:\Users\jdn\AppData\Local\Arduino15\packages" -tools "D:\Pobrane\arduino-1.6.6\tools-builder" -tools "D:\Pobrane\arduino-1.6.6\hardware\tools\avr" -tools "C:\Users\jdn\AppData\Local\Arduino15\packages" -built-in-libraries "D:\Pobrane\arduino-1.6.6\libraries" -libraries "C:\Users\jdn\Documents\Arduino\libraries" -fqbn=arduino:sam:arduino_due_x_dbg -vid-pid=0X2341_0X003D -ide-version=10606 -build-path "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\examples\WebServer\WebServer.ino"
Warning: platform.txt from core 'Arduino ARM (32-bits) Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI\SPI.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dhcp.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Ethernet.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\EthernetClient.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\EthernetServer.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\EthernetUdp.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\socket.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -w -x c++ -M -MG -MP -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++"  -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf  -w -x c++ -E -CC -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"'    "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/"   "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp"
"D:\Pobrane\arduino-1.6.6\tools-builder\ctags\5.8-arduino2/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\preproc\ctags_target.cpp"
"D:\Pobrane\arduino-1.6.6\tools-builder\ctags\5.8-arduino2/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\preproc\ctags_target.cpp"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\sketch\WebServer.ino.cpp.o"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI\SPI.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\SPI\SPI.cpp.o"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dhcp.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\Dhcp.cpp.o"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\Dns.cpp.o"
In file included from D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:7:0:

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp: In member function 'uint16_t DNSClient::ProcessResponse(uint16_t, IPAddress&)':

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:267:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     uint16_t header_flags = htons(*((uint16_t*)&header[2]));

                                                          ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility/util.h:4:22: note: in definition of macro 'htons'

 #define htons(x) ( ((x)<< 8 & 0xFF00) | \

                      ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:267:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     uint16_t header_flags = htons(*((uint16_t*)&header[2]));

                                                          ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility/util.h:5:22: note: in definition of macro 'htons'

                    ((x)>> 8 & 0x00FF) )

                      ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:269:50: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     if ( ( iRequestId != (*((uint16_t*)&header[0])) ) ||

                                                  ^

In file included from D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:7:0:

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:286:57: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     uint16_t answerCount = htons(*((uint16_t*)&header[6]));

                                                         ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility/util.h:4:22: note: in definition of macro 'htons'

 #define htons(x) ( ((x)<< 8 & 0xFF00) | \

                      ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:286:57: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     uint16_t answerCount = htons(*((uint16_t*)&header[6]));

                                                         ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility/util.h:5:22: note: in definition of macro 'htons'

                    ((x)>> 8 & 0x00FF) )

                      ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:295:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     for (uint16_t i =0; i < htons(*((uint16_t*)&header[4])); i++)

                                                          ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility/util.h:4:22: note: in definition of macro 'htons'

 #define htons(x) ( ((x)<< 8 & 0xFF00) | \

                      ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Dns.cpp:295:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

     for (uint16_t i =0; i < htons(*((uint16_t*)&header[4])); i++)

                                                          ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility/util.h:5:22: note: in definition of macro 'htons'

                    ((x)>> 8 & 0x00FF) )

                      ^

"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\Ethernet.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\Ethernet.cpp.o"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\EthernetClient.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\EthernetClient.cpp.o"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\EthernetServer.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\EthernetServer.cpp.o"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\EthernetUdp.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\EthernetUdp.cpp.o"
"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\socket.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\utility\socket.cpp.o"
D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\socket.cpp:365:6: warning: unused parameter 's' [-Wunused-parameter]

 void flush(SOCKET s) {

      ^

"C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10606 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Due"' "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/libsam" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/CMSIS/Include/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\system/CMSIS/Device/ATMEL/" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\cores\arduino" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\variants\arduino_due_x" "-ID:\Pobrane\arduino-1.6.6\libraries\Ethernet\src" "-IC:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI" "D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp" -o "C:\Users\JDN\AppData\Local\Temp\build1a94c3fade059878028b246e557b4116.tmp\libraries\Ethernet\utility\w5100.cpp.o"
D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp: In member function 'void W5100Class::init()':

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp:33:13: error: 'SPI_CS' was not declared in this scope

   SPI.begin(SPI_CS);

             ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp: In static member function 'static uint8_t W5100Class::write(uint16_t, uint8_t)':

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp:147:16: error: 'SPI_CS' was not declared in this scope

   SPI.transfer(SPI_CS, 0xF0, SPI_CONTINUE);

                ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp: In static member function 'static uint16_t W5100Class::write(uint16_t, const uint8_t*, uint16_t)':

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp:168:18: error: 'SPI_CS' was not declared in this scope

     SPI.transfer(SPI_CS, 0xF0, SPI_CONTINUE);

                  ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp: In static member function 'static uint8_t W5100Class::read(uint16_t)':

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp:188:16: error: 'SPI_CS' was not declared in this scope

   SPI.transfer(SPI_CS, 0x0F, SPI_CONTINUE);

                ^

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp: In static member function 'static uint16_t W5100Class::read(uint16_t, uint8_t*, uint16_t)':

D:\Pobrane\arduino-1.6.6\libraries\Ethernet\src\utility\w5100.cpp:209:18: error: 'SPI_CS' was not declared in this scope

     SPI.transfer(SPI_CS, 0x0F, SPI_CONTINUE);

                  ^

Using library SPI at version 1.0 in folder: C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI 
Using library Ethernet at version 1.1.0 in folder: D:\Pobrane\arduino-1.6.6\libraries\Ethernet 
exit status 1
Error compiling.
Warning: platform.txt from core 'Arduino ARM (32-bits) Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.

**Comment by cmaglie** [comment]
@qbahn21 
sorry for the late answer..
The IDE is taking the 1.1.0 version from the install folder:

```
Using library SPI at version 1.0 in folder: C:\Users\jdn\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.5\libraries\SPI Using library Ethernet at version 1.1.0 in folder: D:\Pobrane\arduino-1.6.6\libraries\Ethernet
```

but unfortunately this won't give any clue on why the list of available library is not being updated.
May you check the file in your `%LOCALAPPDATA%\Arduino15\library_index.json` and see if it lists the Ethernet library version 1.1.1? (try to search for `1.1.1`)

Thanks!

**Comment by qbahn21** [comment]
Hi.
No problem. Meanwhile I've deleted folder %LOCALAPPDATA%\Arduino15. It
helped. So problem is fixed. Thanks!
Regards.
Jakub

2015-11-09 11:01 GMT+01:00 Cristian Maglie <notifications@github.com>:

**Comment by NitrofMtl** [comment]
I've got the same problem of updating Ethernet lib, still stuck with version 1.0.5... I've try to delete arduino15 folder but in my case doesn't fix the problem...

anyway to install it manually maybe ??
