### ISSUE TITLE
Banner re-size issue on Launching IDE

### ISSUE THREAD

**Issue by sh-aks** [arduino/Arduino#4215]
It starts with this image
![issue](https://cloud.githubusercontent.com/assets/5464880/11389613/737b4d0e-9368-11e5-9bdc-8c8703f749b0.png)

after a few seconds
![image](https://cloud.githubusercontent.com/assets/5464880/11389627/92664962-9368-11e5-95bc-db7853b22a1a.png)

then IDE opens.

**Comment by ffissore** [comment]
Resize is expected, but should be an instant. Does it last for longer? You have camstudio: can you record a video?

**Comment by sh-aks** [comment]
It takes a bit longer. Change happening is visible.

Link to the video:
https://drive.google.com/file/d/0B9E0W6W6Y7p5Zml1YWNKUzBuNzg/view?usp=sharing

**Comment by ffissore** [comment]
I see. Thank you very much. I'll try to make it a little more reactive

**Comment by ffissore** [comment]
@sh-aks can you try latest hourly? I've updated the component we use to make .exe files (that the one showing the first, slightly larger splash screen), although I fear this won't fix your issue

**Comment by sh-aks** [comment]
@ffissore : The Problem is still persistent in the latest hourly .

*Hourly still comes in a folder called "arduino-nightly".

**Comment by ffissore** [comment]
Yep, we didn't change the file name. 

I've just pushed a patch for launch4j, which is the tool we use to make .exe files. It has a delay of 1 sec, now it's 100ms. Can you download the windows hourly and try again? http://www.arduino.cc/en/Main/Software#hourly

**Comment by sh-aks** [comment]
@ffissore : The problem is still there in this build as well.

Would you need another video?

**Comment by ffissore** [comment]
yes pls

**Comment by sh-aks** [comment]
Video:
https://drive.google.com/file/d/0B9E0W6W6Y7p5RWxSNG1zMTRMUW8/view?usp=sharing

**Comment by ffissore** [comment]
Ok, my patch doesn't work because launch4j comes with its own precompiled .o files, so patching source .c files is pointless. I've sent the patch upstream https://sourceforge.net/p/launch4j/git/merge-requests/7/. Hopefully it will get merged and a new launch4j will be released

**Comment by CurveShot** [comment]
Hi, I might be having a problem similar to this one, however my banner is significantly smaller, and leads to a tiny IDE.

There are some screenshots in the forum post I mentioned 

http://forum.arduino.cc/index.php?topic=368650.0

**Comment by cmaglie** [comment]
@sh-aks @CurveShot 
Can you test the latest hourly build? I think that this problem has been solved (together with a bunch of other problems) with #4376, here some references:

https://github.com/arduino/Arduino/pull/4376#issuecomment-171374850
https://github.com/cmaglie/Arduino/commit/885a51709938ccba2c317f155591e8df52a17059
https://github.com/arduino/Arduino/pull/4376#issuecomment-175102003

**Comment by CurveShot** [comment]
Looks good @cmaglie

**Comment by sh-aks** [comment]
@cmaglie: Solved for me too in 1.6.8

Apologies for delay.
