### ISSUE TITLE
Arduino 101 concatenating float/double to string as wrong value for -1 to 0

### ISSUE THREAD

**Issue by sanelss** [arduino/Arduino#4919]
When adding a float/double type between the values of -1 to 0 it returns it as a positive number.. example code:

```
void setup() {
  Serial.begin(115200);
}

void loop() {
  String s="";
  float db=-0.5;
  //db+=1.1; //doing this will make the string print positive 0.6 so the value is correct
  s+=db;  //when adding double/float type to string you get a positive number for values of -1 to 0
  Serial.println(s);
  delay(100);
}
```

**Comment by facchinm** [comment]
Hi @sanelss ,
the issue had been fixed in mainline with this commit (https://github.com/01org/corelibs-arduino101/commit/7bd93b3baf802481282e32240fcfc1f941e36561), it will be published soon as `Curie core 1.0.6`.
Closing as already fixed

**Comment by sanelss** [comment]
Thank you much for the quick reply. I have manually modified the file to add fix though i think this should have been published immediately once caught as I see it as a major bug

**Comment by sanelss** [comment]
Upon further investigation when doing this modification by itself I still get the same behavior as before. this does not appear to be a fix for the issue

**Comment by facchinm** [comment]
Sorry, maybe I linked you the wrong commit, however if you apply all the post 1.0.5 patches it works (tested :smile: )

**Comment by facchinm** [comment]
And Intel has almost monthly release schedule, so it won't take longer before it gets released

**Comment by sanelss** [comment]
Just a headsup, pulling the latest build does indeed fix the issue(though you did say you tested it by still) :D so yea the commit you posted isn't enough/right part but it works now.

**Comment by facchinm** [comment]
Ok, the right commit was https://github.com/01org/corelibs-arduino101/commit/a54f5132630fb2825e27d84cf4ddf3d8ee22192a , thanks for reporting !

**Comment by lancelon** [comment]
Hi Sanel please can you contact me? Thanks
