### ISSUE TITLE
Add RGBLEDBlender library

### ISSUE THREAD

**Issue by ESikich** [arduino/Arduino#5513]
Hi, I've created a library for easy color blending on an RGB LED.

https://github.com/ESikich/RGBLEDBlender.git

Thanks much,
Erik

**Comment by agdl** [comment]
Hi please fix library.properties according to the tag

https://github.com/ESikich/RGBLEDBlender/blob/1.1.3/library.properties

**Comment by ESikich** [comment]
Fixed.

**Comment by cmaglie** [comment]
I've added the library to the library manager, btw the problem with release 1.1.3 is not fixed.
The library.properties and the tag do not match, as you can see here:

https://github.com/ESikich/RGBLEDBlender/blob/1.1.3/library.properties

the tag is "1.1.3" but library.properties shows "1.1.2".

You can fix this by strictly following these steps:

1) remove the tag 1.1.3
2) fix library.properties and set version to 1.1.3
3) commit and push
4) re-add the tag 1.1.3 (**after** doing 2 and 3)

Once done, the change is automatically picked up by our servers within an hour, no need to further comment here.
