### ISSUE TITLE
Library Manager display problem after installing library from a single search result

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#7793]
Using Arduino 1.8.6 Hourly Build 2018-07-11 05:33 or Arduino IDE Beta build 75 on Windows 10 64 bit

1. Sketch > Include Library > Manage Libraries...
2. Do a search that only returns a single result.
3. Install or update to a different version of the library. After the process finishes, all but the top line of the library listing is cut off.

Hovering the mouse pointer over or clicking on the listing does not cause the full thing to appear again.

The problem does not occur with Arduino IDE 1.8.5.

Problem:
![lmbug](https://user-images.githubusercontent.com/8572152/42852436-6220b942-89e5-11e8-8c1a-de4e1fef4f51.png)

After the same process using Arduino IDE 1.8.5:
![lm185](https://user-images.githubusercontent.com/8572152/42852447-6c3eec00-89e5-11e8-9581-3cf49c002e0e.png)

**Comment by facchinm** [comment]
Hi @per1234 , thanks for spotting all these stuff! This should be solved by 0ee0fcc018d2bfa7c5a7ba384158a6ec27da1681, I just pushed it in master and an hourly build should be available soon :wink: 
Feel free to close the issue if the fix is effective! Thanks

**Comment by per1234** [comment]
@facchinm I just downloaded the hourly build. It still says 2018-07-11 05:33 in the title bar and this issue still occurs.

**Comment by facchinm** [comment]
Hi @per1234 , there was a issue in that commit; I didn't spot it because I didn't run `ant clean` :disappointed: Now it should be fixed in both master and beta channels and the hourly builds are ongoing :slightly_smiling_face:
