### ISSUE TITLE
Comparison method BUG

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/Arduino#9537]
Open IDE 1.8.10
Selected Library Manager
The following text is observed in the lower left of the open box.
"Comparison method violates its general contract!"
[Also posted here](https://forum.arduino.cc/index.php?topic=654414.msg4410070#msg4410070)

![2019-12-18 at 10-27-16](https://user-images.githubusercontent.com/8212730/71099775-d36f3580-2181-11ea-8c34-d3ddb0e647b4.jpg)

**Comment by cmaglie** [comment]
This has been fixed in IDE 1.8.12: #9748

**Comment by kevinsegal** [comment]
I'm still seeing this error in 1.8.12.
![Screen Shot 2021-03-23 at 11 39 02 PM](https://user-images.githubusercontent.com/7696145/112266267-02037800-8c31-11eb-9f68-f94b0085a824.png)
